2025-07-21 19:09:09 | challenge_manager | ERROR | _load_challenges:42 | Failed to load challenge challenges/level3_application_launch.py: ~/.Xauthority: [Errno 2] No such file or directory: '/home/runner/.Xauthority'
2025-07-21 19:09:09 | challenge_manager | ERROR | _load_challenges:42 | Failed to load challenge challenges/level4_ui_navigation.py: ~/.Xauthority: [Errno 2] No such file or directory: '/home/runner/.Xauthority'
2025-07-21 19:09:09 | challenge_manager | ERROR | _load_challenges:42 | Failed to load challenge challenges/level5_complex_tasks.py: ~/.Xauthority: [Errno 2] No such file or directory: '/home/runner/.Xauthority'
2025-07-21 19:09:09 | challenge_manager | ERROR | _load_challenges:42 | Failed to load challenge challenges/level6_file_management.py: ~/.Xauthority: [Errno 2] No such file or directory: '/home/runner/.Xauthority'
2025-07-21 19:09:09 | challenge_manager | ERROR | _load_challenges:42 | Failed to load challenge challenges/level7_advanced_operations.py: ~/.Xauthority: [Errno 2] No such file or directory: '/home/runner/.Xauthority'
2025-07-21 19:09:09 | challenge_manager | ERROR | _load_challenges:42 | Failed to load challenge challenges/level3_application_launch.py: ~/.Xauthority: [Errno 2] No such file or directory: '/home/runner/.Xauthority'
2025-07-21 19:09:09 | challenge_manager | ERROR | _load_challenges:42 | Failed to load challenge challenges/level4_ui_navigation.py: ~/.Xauthority: [Errno 2] No such file or directory: '/home/runner/.Xauthority'
2025-07-21 19:09:09 | challenge_manager | ERROR | _load_challenges:42 | Failed to load challenge challenges/level5_complex_tasks.py: ~/.Xauthority: [Errno 2] No such file or directory: '/home/runner/.Xauthority'
2025-07-21 19:09:09 | challenge_manager | ERROR | _load_challenges:42 | Failed to load challenge challenges/level6_file_management.py: ~/.Xauthority: [Errno 2] No such file or directory: '/home/runner/.Xauthority'
2025-07-21 19:09:09 | challenge_manager | ERROR | _load_challenges:42 | Failed to load challenge challenges/level7_advanced_operations.py: ~/.Xauthority: [Errno 2] No such file or directory: '/home/runner/.Xauthority'
